"""user per-user daily_limit override

Revision ID: 4c3fb0650b1f
Revises: d3942df9822e
Create Date: 2026-07-18 01:18:25.353161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c3fb0650b1f'
down_revision: Union[str, Sequence[str], None] = 'd3942df9822e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('daily_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_limit')
    # ### end Alembic commands ###
