"""roles, threads rename, daily_usage

Revision ID: 9a5d173a0cf9
Revises: 1b33d9e2ba80
Create Date: 2026-07-17 15:59:58.518063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a5d173a0cf9'
down_revision: Union[str, Sequence[str], None] = '1b33d9e2ba80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_usage',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'day')
    )
    op.create_table('threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('csv_name', sa.String(length=512), nullable=False),
    sa.Column('csv_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threads_user_id'), 'threads', ['user_id'], unique=False)
    op.add_column('users', sa.Column('role', sa.String(length=16), server_default='user', nullable=False))
    # charts: swap the dataset_id FK/column for thread_id (table is empty) —
    # remove the dependency on datasets BEFORE dropping that table.
    op.drop_constraint(op.f('charts_dataset_id_fkey'), 'charts', type_='foreignkey')
    op.drop_index(op.f('ix_charts_dataset_id'), table_name='charts')
    op.drop_column('charts', 'dataset_id')
    op.add_column('charts', sa.Column('thread_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_charts_thread_id'), 'charts', ['thread_id'], unique=False)
    op.create_foreign_key(None, 'charts', 'threads', ['thread_id'], ['id'], ondelete='CASCADE')
    # datasets now has no dependents
    op.drop_index(op.f('ix_datasets_user_id'), table_name='datasets')
    op.drop_table('datasets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.add_column('charts', sa.Column('dataset_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'charts', type_='foreignkey')
    op.create_foreign_key(op.f('charts_dataset_id_fkey'), 'charts', 'datasets', ['dataset_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_charts_thread_id'), table_name='charts')
    op.create_index(op.f('ix_charts_dataset_id'), 'charts', ['dataset_id'], unique=False)
    op.drop_column('charts', 'thread_id')
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('datasets_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('datasets_pkey'))
    )
    op.create_index(op.f('ix_datasets_user_id'), 'datasets', ['user_id'], unique=False)
    op.drop_index(op.f('ix_threads_user_id'), table_name='threads')
    op.drop_table('threads')
    op.drop_table('daily_usage')
    # ### end Alembic commands ###
