"""user visits + last_seen_at

Revision ID: d3942df9822e
Revises: 9a5d173a0cf9
Create Date: 2026-07-17 23:41:17.803195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3942df9822e'
down_revision: Union[str, Sequence[str], None] = '9a5d173a0cf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('visits', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen_at')
    op.drop_column('users', 'visits')
    # ### end Alembic commands ###
